[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "usgs-splib07-processor"
version = "1.0.0"
description = "Process USGS Spectral Library v7.0 data into callable interpolation functions for remote sensing & spectroscopy."
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "scipy",
    "tqdm"
]

[project.optional-dependencies]
dev = ["pytest", "black", "isort"]
